### ISSUE TITLE
top-level includes are not converted

### ISSUE THREAD

**Issue by steebchen** [ManuelSch/sass-scss-converter#18]
```sass
+dark
	.card
		background: white
```

is converted into

```scss
+ dark {
    .card {
		background: white
    }
}
```

but should be 

```scss
@include dark {
    .card {
		background: white
    }
}
```

This only happens on the top level.
