### ISSUE TITLE
Does not properly work with if-else

### ISSUE THREAD

**Issue by antsif-a** [ManuelSch/sass-scss-converter#23]
Input SCSS:
```scss
@mixin centered($horizontal: true, $vertical: true) {
  position: absolute;
  @if ($horizontal and $vertical) {
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
  } @else if ($horizontal) {
    left: 50%;
    transform: translate(-50%, 0);
  } @else if ($vertical) {
    top: 50%;
    transform: translate(0, -50%);
  }
}
```
Output Sass:
```sass

@mixin centered($horizontal: true, $vertical: true)
  position: absolute
  @if ($horizontal and $vertical)
    top: 50%
    left: 50%
    transform: translate(-50%, -50%)

    left: 50%
    transform: translate(-50%, 0)

    top: 50%
    transform: translate(0, -50%)
```

The output lacks some `else-if`-s.
