### ISSUE TITLE
Private placeholders are missing percent character

### ISSUE THREAD

**Issue by jameswilson** [ManuelSch/sass-scss-converter#49]
## Affects SASS to SCSS

SASS Input:
```sass
%placeholder
  color: red
.my-thing
  @extend %placeholder
```

Expected SCSS Output:
```scss
%placeholder {
  color: red;
}
.my-thing {
  @extend %placeholder;
}
```

Actual SCSS Output:
```scss
placeholder {
  color: red;
}
.my-thing {
  @extend placeholder;
}
```

## Affects SCSS to SASS

SCSS Input:
```scss
%placeholder {
  color: red;
}
.my-thing {
  @extend %placeholder;
}
```

Expected SASS Output:
```sass
%placeholder
  color: red
.my-thing
  @extend %placeholder
```

Actual SASS Output:
```sass
placeholder
  color: red
.my-thing
  @extend placeholder
```
