### ISSUE TITLE
Incorrect sass to scss conversion using nth-child selector

### ISSUE THREAD

**Issue by jhonnyizidoro** [ManuelSch/sass-scss-converter#54]
## Not working ❌

The sass to scss conversion is giving the wrong output when using the selectors bellow:
- `nth-child(n + *any-number*)`
- `nth-child(-n + *any-number*)`

## Working ✅
The following selectors are working properly
- `nth-child(odd)`
- `nth-child(event)`
- `nth-child(1)`
- `nth-child(*any-number*)`

## Example

Input▶️
```css
.cards
  &__wrapper
    +columns(3)
  &__wrapper
    padding-bottom: 50px
  &__wrapper:nth-child(3n+1)
    padding-right: 25px
  &__wrapper:nth-child(3n+2)
    padding-left: 12px
    padding-right: 12px
  &__wrapper:nth-child(3n+3)
    padding-left: 25px
```

Output ❌
```css
.cards {
  &__wrapper {
    @include columns(3);
  }
  &__wrapper {
    padding-bottom: 50px;
  }
  false {
    padding-right: 25px;
  }
  false {
    padding-left: 12px;
    padding-right: 12px;
  }
  false {
    padding-left: 25px;
  }
}
```

Expected output ✅
```css
.cards {
  &__wrapper {
    @include columns(3);
  }
  &__wrapper {
    padding-bottom: 50px;
  }
  &__wrapper:nth-child(3n+1) {
    padding-right: 25px;
  }
  &__wrapper:nth-child(3n+2) {
    padding-left: 12px;
    padding-right: 12px;
  }
  &__wrapper:nth-child(3n+3) {
    padding-left: 25px;
  }
}
```
